# Generated by Django 4.2.13 on 2024-06-22 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_path', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('*', 'All Files'), ('TARGZ', '*.tar.gz'), ('ZIP', '*.zip'), ('DAT1', '*.dat1'), ('DAT2', '*.dat2')], default='*', max_length=10)),
                ('last_lookup_time', models.DateTimeField()),
                ('auto_delete_enabled', models.BooleanField(default=False, help_text='Auto delete after file transfer completed.')),
                ('is_active', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('updates_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Recommended format: 'source':'/path' ==> 'destination':'/path'", max_length=255)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('NORMAL', 'Normal')], default='NORMAL', max_length=10)),
                ('cron_schedule', models.CharField(max_length=20)),
                ('files_in_queue', models.IntegerField()),
                ('last_run', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst_data_path', to='api.datapath')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_data_path', to='api.datapath')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('hostname', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=30)),
                ('source_type', models.CharField(choices=[('SFTP', 'SFTP'), ('LOCAL_COPY', 'Local Copy'), ('HTTP', 'HTTP'), ('HTTPS', 'HTTPS')], default='LOCALCOPY', max_length=10)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('is_acitive', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FileRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('filesize_in_mb', models.BigIntegerField()),
                ('transfer_status', models.CharField(max_length=255)),
                ('transfer_rate', models.CharField(max_length=255)),
                ('archived', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('managed_by_pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datapipeline')),
            ],
        ),
        migrations.AddField(
            model_name='datapath',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.source'),
        ),
    ]
