# Generated by Django 4.2.13 on 2024-06-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="source",
            old_name="is_acitive",
            new_name="is_active",
        ),
        migrations.AddField(
            model_name="source",
            name="system_message",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
