# Generated by Django 4.2.13 on 2024-06-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_is_acitive_source_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="port",
            field=models.CharField(default="22", max_length=10),
        ),
    ]
