# Generated by Django 4.2.13 on 2024-06-22 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_archival_days', models.IntegerField()),
                ('default_percent_threshold', models.IntegerField(default=80)),
                ('is_active', models.BooleanField(default=False)),
                ('last_executed', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('auto_archival_paths', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datapath')),
            ],
        ),
    ]
